[package]
name = "rust_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
noise = "0.7"
rand = "0.8"

derive_more = "0.99"
# log = "0.4"
# pretty_env_logger = "0.4"